config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("news/", views.NewsListView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path(
        "news/<int:pk>/detail",
        views.NewsDetailView.as_view(),
        name="news_detail",
    ),
    path(
        "news/<int:pk>/update",
        views.NewsUpdateView.as_view(),
        name="news_update",
    ),
    path(
        "news/<int:pk>/delete",
        views.NewsDeleteView.as_view(),
        name="news_delete",
    ),
    path(
        "courses/",
        cache_page(60 * 5)(views.CoursesListView.as_view()),  # 5 minutes
        name="courses",
    ),
    path(
        "courses/<int:pk>/",
        views.CoursesDetailView.as_view(),
        name="courses_detail",
    ),
    path(
        "course_feedback/",
        views.CourseFeedbackFormProcessView.as_view(),
        name="course_feedback",
    ),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

mainapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preambule = models.CharField(max_length=1024, verbose_name="Preambule")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")
        ordering = ("-created",)


class CoursesManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class Courses(models.Model):
    objects = CoursesManager()

    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class CourseFeedback(models.Model):
    RATING = ((5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"), (1, "⭐"))
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name=_("Course"))
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    feedback = models.TextField(default=_("No feedback"), verbose_name=_("Feedback"))
    rating = models.SmallIntegerField(choices=RATING, default=5, verbose_name=_("Rating"))
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course} ({self.user})"


class Lesson(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")

templates/includes/main_menu.html
{% extends 'base.html' %}

{% block title %}
Новости
{% endblock title %}

{% block content %}

{% if page_num %}
<div class="card my-2">
  <div class="card-body">
    <p class="card-text">Текущая страница: {{ page_num }}</p>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="col-lg-8">

    {% for item in object_list %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ item.created|date:"Y-m-d h-i-s" }}
        </h6>
        <p class="card-text">{{ item.preambule }}</p>
        <div class="row">
          <div class="col">
            <a href="{% url 'mainapp:news_detail' pk=item.pk %}"
              class="card-link">Подробнее</a>
          </div>
          {% if perms.mainapp.change_news %}
          <div class="col-1 text-center">
            <a href="{% url 'mainapp:news_update' pk=item.pk %}">
              <i class="far fa-edit"></i>
            </a>
          </div>
          {% endif %}
          {% if perms.mainapp.delete_news %}
          <div class="col-1 text-center">
            <a href="{% url 'mainapp:news_delete' pk=item.pk %}">
              <i class="far fa-trash-alt"></i>
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}

  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit"
            class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>

    {% if perms.mainapp.add_news %}
    <a class="btn btn-primary btn-block" role="button"
      href="{% url 'mainapp:news_create' %}">Добавить новость</a>
    {% endif %}

  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link"
          href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

      {% for item in page_obj.paginator.page_range %}
      <li class="page-item
        {% if item == page_obj.number %}active{% endif %}">
        <a class="page-link" href="?page={{ item }}">{{ item }}</a>
      </li>
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link"
          href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
  </nav>
</div>

{% endblock content %}

templates/includes/messages.html
<div class="position-absolute w-100" style="z-index: 1;">
    <div aria-live="polite" aria-atomic="true" class="m-2">
      <!-- Position it -->
      <div class="d-flex align-items-end flex-column">
  
        {% for message in messages %}
        <!-- Then put toasts within -->
        <div class="toast flex-fill w-100
      {% if message.level == 30 %}
      border-warning
      {% endif %}
        " role="alert" aria-live="assertive" aria-atomic="true"
          style="right: 0;">
          <div class="toast-header">
            <span class="mr-2"><i class="far fa-envelope"></i></span>
            <strong
              class="mr-auto {% if message.level == 30 %}text-warning{% endif %}">
              {{ message.tags|capfirst }} message</strong>
            <small class="text-muted">just now</small>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"
              aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="toast-body">
            {{ message }}
          </div>
        </div>
        {% if message.level > 20 %}
        <!-- If message will dissapere you will find message in console -->
        <script>
          console.log("{{ message }}");
        </script>
        {% endif %}
  
        {% endfor %}
  
      </div>
  
    </div>
  </div>